name: Label PRs

on:
  - pull_request_target

jobs:
  labeler:
    if: github.actor == 'your-trusted-user'
    uses: GregTech-Engineering/GithubActions/.github/workflows/labeler.yml@main
    secrets: inherit
