name: Label PRs

on:
  - pull_request_target

permissions:
  pull-requests: write

jobs:
  labeler:
    uses: GregTech-Engineering/GithubActions/.github/workflows/labeler.yml@main
    secrets: inherit
