name: Sync Github Folder

on:
  push:
    branches: ['main']
    paths: ['.github/**']

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git switch -C gh/workflow-sync
          git fetch origin
          git checkout origin/main -- .github
          git commit -am "Sync Workflows"
          git push --force --set-upstream origin gh/workflow-sync
